# Generated by Django 5.0.2 on 2024-03-06 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish_detection_app', '0002_url_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 7, 17, 21, 138703, tzinfo=datetime.timezone.utc)),
        ),
    ]
