# Generated by Django 5.0.2 on 2024-03-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish_detection_app', '0003_alter_url_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
